/**
 * /en 영문 미러용 번역 단일 출처 — 제품명·카테고리·태그라인.
 * 맵에 없으면 원문(영문 제품명 등)을 그대로 쓴다.
 */
import type { Project } from '../../../src/data/projects';

const NAME: Record<string, string> = {
  밈캐치: 'MemeCatch',
  '한붓길 정원': 'One-Stroke Garden',
  코스픽: 'CoursePick',
  '골목길 생존기': 'Alley Survivor',
  '동네 칠하기 대작전': 'Paint the Block',
  청년머니가이드: 'YM Money Guide',
  '별빛 온실': 'Starlight Greenhouse',
  '30초 배구왕': '30s Volley King'
};

const CATEGORY: Record<string, string> = {
  'AI 파이프라인': 'AI Pipeline',
  'Agent Skills · 오픈소스': 'Agent Skills · OSS',
  'Web3 · 데이터 대시보드': 'Web3 · Data Dashboard',
  'Web3 · 크립토': 'Web3 · Crypto',
  '게임 · 논리 퍼즐': 'Game · Logic Puzzle',
  '게임 · 방치형 성장': 'Game · Idle Growth',
  '게임 · 스포츠 아케이드': 'Game · Sports Arcade',
  '게임 · 영역 점령': 'Game · Territory',
  '게임 · 하이퍼캐주얼': 'Game · Hypercasual',
  '사진 · 그룹 공유': 'Photos · Group Sharing',
  '생산성 도구': 'Productivity Tool',
  '성경 · 커뮤니티': 'Bible · Community',
  '아웃도어 · 큐레이션': 'Outdoor · Curation',
  '여행 플랫폼': 'Travel Platform',
  '위치기반 소셜': 'Location Social',
  '전자계약 · 운영 플랫폼': 'E-Contract Platform',
  '정책 · 금융 큐레이션': 'Policy · Finance Curation',
  '정책 · 생활 금융': 'Policy · Personal Finance',
  '지식 시스템 · 문서': 'Knowledge System · Docs',
  '트렌드 사전 · 커뮤니티': 'Trend Dictionary · Community'
};

const TAGLINE: Record<string, string> = {
  밈캐치: 'That meme, in 3 seconds — the Korean meme trend dictionary',
  asyncraft: 'A zero-dependency toolkit that makes failing async flows robust',
  'TorisUI Kit': 'Fluid, accessible, dark-first — a React UI system for shipping fast',
  TraceDesk: 'An interactive personal activity journal for replaying your day',
  devPulse: 'Dev-news card news & videos generated by a local LLM',
  청년머니가이드: 'Youth policy & finance benefits that match you, in one place',
  'toris-docs': 'A personal knowledge system built on Markdown & Obsidian',
  'Product Growth Skills': 'Open-source agent skills for product growth workflows'
};

export const enName = (p: Project) => NAME[p.name] ?? p.name;
export const enCat = (p: Project) => CATEGORY[p.category] ?? p.category;
export const enTagline = (p: Project) => TAGLINE[p.name] ?? p.tagline;
